comment: false

codecov: 
 token: 91f619c5-d1ff-4e86-9a1b-a1c5dd4591a8

coverage:
  status:
    patch:
      default:
        informational: true
        target: auto
        threshold: 1.0
    project:
      default:
        informational: true
        target: auto
        threshold: 1.0
